# Generated by Django 5.1.1 on 2024-10-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietarysuggestion',
            old_name='meal_ideas',
            new_name='suggestions_json',
        ),
        migrations.RemoveField(
            model_name='dietarysuggestion',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='dietarysuggestion',
            name='portion_size',
        ),
        migrations.RemoveField(
            model_name='dietarysuggestion',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='dietarysuggestion',
            name='snacks',
        ),
    ]
