# Generated by Django 5.1.1 on 2024-10-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_rename_meal_ideas_dietarysuggestion_suggestions_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietarysuggestion',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dietarysuggestion',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
