# Generated by Django 5.1.1 on 2024-10-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_dietarysuggestion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarysuggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietarysuggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
