# Generated by Django 5.1.1 on 2024-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gl_unit',
            field=models.CharField(choices=[('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l')], default='md/dl', max_length=20),
        ),
    ]
