# Generated by Django 5.1.1 on 2024-10-10 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_glucose_level_entry_glucose_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], max_length=20)),
                ('blood_sugar_check', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('sometimes', 'Sometimes')], max_length=20)),
                ('active_lifestyle', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('sometimes', 'Sometimes')], max_length=20)),
                ('other_illnesses', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('diabetes_medication', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('family_history', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('sugar_intake', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10)),
                ('symptoms', models.CharField(choices=[('frequent_thirst', 'Frequent Thirst'), ('frequent_urination', 'Frequent Urination'), ('unexplained_weight_loss', 'Unexplained Weight Loss'), ('none', 'None')], max_length=50)),
                ('high_blood_pressure', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('gestational_diabetes', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
