# Generated by Django 5.1.1 on 2024-10-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userhealthsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userhealthsurvey',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='userhealthsurvey',
            name='symptoms',
            field=models.ManyToManyField(to='main.symptom'),
        ),
    ]
