# Generated by Django 5.1.2 on 2024-10-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_symptom_remove_userhealthsurvey_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthsurvey',
            name='high_blood_pressure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], max_length=20),
        ),
    ]
